name: CI

on:
 workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      dev:
        description: 'Deploy to dev'
        default: false
        type: boolean
      staging:
        description: 'Deploy to staging'
        default: false
        type: boolean
      qat:
        description: 'Deploy to qat'
        default: false
        type: boolean
      prod:
        description: 'Deploy to prod'
        default: false
        type: boolean

jobs:
  print_context:
    runs-on:
     group: Default
     labels: [self-hosted]
    steps:
      - env:
         CHK_DEV: ${{ inputs.dev }}
         CHK_STAGING: ${{ inputs.staging }}
         CHK_QAT: ${{ inputs.qat }}
         CHK_PROD: ${{ inputs.prod }}
         ENV_VAR: qat
        run: |
          echo CHK_DEV
      - name: Set ENV_VAR as comma-separated values
        run: |
         ENV_VAR=""
         if [[ "${{ inputs.dev }}" == "true" ]]; then
           ENV_VAR="${ENV_VAR}dev,"
         fi

         if [[ "${{ inputs.staging }}" == "true" ]]; then
           ENV_VAR="${ENV_VAR}staging,"
         fi

         if [[ "${{ inputs.qat }}" == "true" ]]; then
           ENV_VAR="${ENV_VAR}qat,"
         fi

         if [[ "${{ inputs.prod }}" == "true" ]]; then
           ENV_VAR="${ENV_VAR}prod,"
         fi
         
         # Remove trailing comma if present
         ENV_VAR="${ENV_VAR%,}"
         echo "ENV_VAR=$ENV_VAR" >> $GITHUB_ENV
      - name: Use ENV_VAR in next step
        run: |
         echo "The environment is: $ENV_VAR"
        env:
         ENV_VAR: ${{ env.ENV_VAR }}

 