name: CI

on:
 workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      dev:
        description: 'Deploy to dev'
        default: false
        type: boolean
      staging:
        description: 'Deploy to staging'
        default: false
        type: boolean
      qat:
        description: 'Deploy to qat'
        default: false
        type: boolean
      prod:
        description: 'Deploy to prod'
        default: false
        type: boolean

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
         CHK_DEV: ${{ inputs.dev }}
         CHK_STAGING: ${{ inputs.staging }}
         CHK_QAT: ${{ inputs.qat }}
         CHK_PROD: ${{ inputs.prod }}
         ENV_VAR: qat
        run: |
          echo CHK_DEV
      - name: Set ENV_VAR based on input
        run: |
         if [[ "${{ inputs.prod }}" == "true" ]]; then
          ENV_VAR=prod
         elif [[ "${{ inputs.qat }}" == "true" ]]; then
          ENV_VAR=qat
         elif [[ "${{ inputs.staging }}" == "true" ]]; then
          ENV_VAR=staging
         elif [[ "${{ inputs.dev }}" == "true" ]]; then
          ENV_VAR=dev
         else
          ENV_VAR=none
         fi
         echo "ENV_VAR=$ENV_VAR" >> $GITHUB_ENV
      - name: Use ENV_VAR in next step
        run: |
         echo "The environment is: $ENV_VAR"
        env:
         ENV_VAR: ${{ env.ENV_VAR }}

 